### ISSUE TITLE
Support scikit-learn compatible

### ISSUE THREAD

**Issue by arandomgoodguy** [WhatAShot/ExcelFormer#3]
Hi, great work!

Is there any chance for ExcelFormer to support scikit-learn fit API, so we can use something like ExcelFormerClassifier.fit().

In your another repo, TabCaps, model can be fitted by TabCapsClassifier.fit(), which is good.

It can help compare performance of multiple tabular models if they are all in one format, thanks!

**Comment by jyansir** [comment]
> Hi, great work!
> 
> Is there any chance for ExcelFormer to support scikit-learn fit API, so we can use something like ExcelFormerClassifier.fit().
> 
> In your another repo, TabCaps, model can be fitted by TabCapsClassifier.fit(), which is good.
> 
> It can help compare performance of multiple tabular models if they are all in one format, thanks!

Hello, many thanks for your attention to our work! And yes, we do plan to reorganize ExcelFormer codes to support uniform APIs as machine learning package scikit-learn, our another work [T2G-Former](https://github.com/jyansir/t2g-former) is also on schedule. The original codes for paper experiment reproduction will be preserved in the personal repo, and the uniform version will appear in our [org repo](https://github.com/pytabular-ai).

We are currently busy in our ongoing research work and will inform you once code reorganization is finished, it won't be late.

**Comment by arandomgoodguy** [comment]
Thanks for your quick response. I look forward to hearing from you soon.
