### ISSUE TITLE
Data to run the code

### ISSUE THREAD

**Issue by wmmxk** [WhatAShot/ExcelFormer#4]
I am so glad to find your work, and finally see a nn that beats tree models.

Would it possible for you to upload the "/data2/yanjianhuan/research/data/tabular/data" to cloud? So it would be easier for me to run the code. I would like to run your code on your data first to do a sanity check first before trying on my data.

**Comment by jEmbiid** [comment]
I'm running into this issue as well, hopefully reproducing the results.

**Comment by WhatAShot** [comment]
Thank you!
They are available at:
https://huggingface.co/datasets/jyansir/excelformer

**Comment by lierlaowang** [comment]
> [wmmxk](/wmmxk)
Hello, have you reproduced the code? I am currently missing the info.json file
