### ISSUE TITLE
The paper results are not reproducible!

### ISSUE THREAD

**Issue by mogvision** [WhatAShot/ExcelFormer#5]
Hi<
Congrats on your great research paper, 
I just ran the code for CA and in the best scenario, I got ~-0.445 which is far from -0.433 reported in the draft! Have you considered any specific constraints in your model during training? I used the default params recommended in the repo.
BWs,

**Comment by WhatAShot** [comment]
Thank you for your interest. We did obtain the result. I am not sure if we use the hyperparameters or the other settings in the same way. For example, the mixup type. Besides, I am not sure the train-val-test splitting is the same. Perhaps you can refer to the original article or try another data set.

**Comment by WhatAShot** [comment]
You may try Hid-Mix and Feat-Mix both. :-)

**Comment by lierlaowang** [comment]
> You may try Hid-Mix and Feat-Mix both. :-)

您好，我在复现的过程中加载您的数据集时，这里的路径缺少文件：
PROJ = Path('/public/home/ExcelFormer-main').absolute().resolve()
EXP = PROJ / 'exp'
DATA = PROJ / 'data'
YANDEX_DATA = PROJ / 'data/tabular/data'
BENCHMARK_DATA = PROJ / 'data/tabular_benchmark'
报错：
FileNotFoundError: [Errno 2] No such file or directory: '/public/home/ExcelFormer-main/data/bank-marketing/info.json'

**Comment by Nadia-Mas** [comment]
Hello, Thank you for sharing the model.
I'm trying to apply your model to my dataset, but I keep encountering an error. I’ve already updated the dataset path in the environment settings, but the issue persists.

Do you have any suggestions or guidance that might help resolve this?

Thank you in advance!
