### ISSUE TITLE
Where can I find the appendix

### ISSUE THREAD

**Issue by isCopyman** [WhatAShot/ExcelFormer#7]
Sorry, I couldn't find the appendix for the paper I downloaded on arxiv. How can I obtain it.

**Comment by WhatAShot** [comment]
Sorry. I uploaded the wrong version. I will replace it with a new one.

**Comment by isCopyman** [comment]
If you have uploaded a new version, can you reply to me here? I still haven't found the new version yet.

**Comment by WhatAShot** [comment]
Sorrrry, I just uploaded it, and I think it would be available on Friday this week or next Monday!
